### ISSUE TITLE
Meal implementation

### ISSUE THREAD

**Issue by h4kureii** [CSC207-UofT/course-project-javacado-s#91]
I finally took a closer look at our Meal implementation.
To be frank, I think the entire Meal subsection is problematic. 

### Here's the issue:
Breakfast, Lunch, and Dinner are functionally identical, because currently, everything takes place in Meal. **This is outdated.**

I believe that code was from back when we had only one Meal class, and just had parameters for Breakfast, Lunch, and Dinner, so it made sense then. However, now that we created subclasses for each MealType, we shouldn't have a HashMap for anything apart from maybe employee types to floats; each specific parameter (respective price, respective number of employees, respective menu, etc.) should be stored in each subclass. Lunch should contain the price of lunch and only lunch. Dinner should contain the menu for dinner and only dinner. And so on and so forth. They should not ever be able to access each other's parameters, but with the current implementation, they are, since it's all located in the parent class.

On a side note, I think it's just plain weird to create setter methods that don't actually set the field? They are called only on initialization, and you could just stuff the code into the constructor. Since our Meal classes act more as "data storage", they don't really need setter methods to begin with.

**Comment by ZS106** [comment]
Agree, I will modify the Meal Class accordingly.

**Comment by ZS106** [comment]
Meal packages is modified accordingly.
(I decide to keep createEmployee() in the Abstract Meal Class)
